services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    hostname: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"
    networks:
      - rinha-net
      - payment-processor

  api-1:
    build: .
    container_name: rinha-api-1
    hostname: rinha-api-1
    command: node gateway/server.js
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://rinha-redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "65MB"
    networks:
      - rinha-net
      - payment-processor

  api-2:
    build: .
    container_name: rinha-api-2
    hostname: rinha-api-2
    command: node gateway/server.js
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://rinha-redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "65MB"
    networks:
      - rinha-net
      - payment-processor

  processor:
    build: .
    container_name: rinha-processor
    hostname: rinha-processor
    command: node processor-worker.js
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://rinha-redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"
    networks:
      - rinha-net
      - payment-processor

  redis:
    image: redis:8.0.3-alpine
    container_name: rinha-redis
    hostname: rinha-redis
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save ""
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true